sudo: required
dist: xenial

language: node_js
node_js: 10

os:
  # - linux
  - osx

env:
  - HAXE_VERSION=latest
  - HAXE_VERSION=nightly
  
install:
  - npm i -g lix
  - lix install haxe $HAXE_VERSION
  - lix download

script:
  - lix run travix interp
  - lix run travix js
  - lix run travix node
  - lix run travix lua
  - lix run travix php
  - lix run travix cpp
  - lix run travix python
  - lix run travix jvm
