sudo: required
dist: trusty

language: node_js
node_js: 8

os:
  - linux
  # - osx

env:
  - HAXE_VERSION=3.4.7
  - HAXE_VERSION=latest
  
install:
  - npm i -g lix
  - lix install haxe $HAXE_VERSION
  - lix download

script:
  - lix run travix js
  - lix run travix node
  - lix run travix lua
  - lix run travix php
  - lix run travix cpp
  - lix run travix hl
  - lix run travix python
